knp_paginator:
    page_range: 3                       # Nombre de pages affichées dans le paginatore.
    default_options:
        page_name: page                 # Nom du paramètre de page dans l'URL
        sort_field_name: sort           # Nom du paramètre de tri dans l'URL
        sort_direction_name: direction  # Nom du paramètre de direction de tri dans l'URL
        distinct: true                  # Si vrai, empêche les doublons dans les résultats
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig' # Modèle pour la pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Modèle pour les liens de tri
